export const servicesData = [
  {
    slug: 'web-development',
    number: '01',
    icon: '🌐',
    titleKey: 'web_dev_title',
    subtitleKey: 'web_dev_subtitle',
    descriptionKey: 'web_dev_desc',
    fullDescriptionKey: 'web_dev_full_desc',
    tools: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL'],
    categoryKey: 'cat_development',
    process: [
      { step: '01', titleKey: 'process_discovery', descKey: 'process_discovery_desc' },
      { step: '02', titleKey: 'process_architecture', descKey: 'process_architecture_desc' },
      { step: '03', titleKey: 'process_development', descKey: 'process_development_desc' },
      { step: '04', titleKey: 'process_launch', descKey: 'process_launch_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-web-1',
        slug: 'e-commerce-platform',
        titleKey: 'cs_ecommerce_title',
        categoryKey: 'cs_web_dev_cat',
        image: 'https://images.unsplash.com/photo-1661956602116-aa6865609028?w=1200&q=80',
        excerptKey: 'cs_ecommerce_excerpt',
        tags: ['Next.js', 'Stripe', 'Sanity CMS'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-web-2',
        slug: 'saas-dashboard',
        titleKey: 'cs_saas_title',
        categoryKey: 'cs_web_dev_cat',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
        excerptKey: 'cs_saas_excerpt',
        tags: ['Next.js', 'TypeScript', 'Recharts'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-web-3',
        slug: 'fintech-web-app',
        titleKey: 'cs_fintech_title',
        categoryKey: 'cs_web_dev_cat',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
        excerptKey: 'cs_fintech_excerpt',
        tags: ['React', 'Node.js', 'PostgreSQL'],
        year: '2024',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'graphics-design',
    number: '02',
    icon: '🎨',
    titleKey: 'graphics_title',
    subtitleKey: 'graphics_subtitle',
    descriptionKey: 'graphics_desc',
    fullDescriptionKey: 'graphics_full_desc',
    tools: ['Illustrator', 'Photoshop', 'Canva', 'After Effects', 'InDesign', 'Figma'],
    categoryKey: 'cat_design',
    process: [
      { step: '01', titleKey: 'process_brief', descKey: 'process_brief_desc' },
      { step: '02', titleKey: 'process_concepts', descKey: 'process_concepts_desc' },
      { step: '03', titleKey: 'process_refinement', descKey: 'process_refinement_desc' },
      { step: '04', titleKey: 'process_delivery', descKey: 'process_delivery_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-gfx-1',
        slug: 'branding-identity',
        titleKey: 'cs_branding_title',
        categoryKey: 'cs_branding_cat',
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&q=80',
        excerptKey: 'cs_branding_excerpt',
        tags: ['Branding', 'Logo', 'Guidelines'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-gfx-2',
        slug: 'logo-design-collection',
        titleKey: 'cs_logo_title',
        categoryKey: 'cs_branding_cat',
        image: 'https://images.unsplash.com/photo-1524532787116-e70228437bbe?w=1200&q=80',
        excerptKey: 'cs_logo_excerpt',
        tags: ['Logo Design', 'Illustrator'],
        year: '2025',
        liveUrl: null,
      },
      {
        id: 'cs-gfx-3',
        slug: 'brand-identity-system',
        titleKey: 'cs_brand_system_title',
        categoryKey: 'cs_branding_cat',
        image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=1200&q=80',
        excerptKey: 'cs_brand_system_excerpt',
        tags: ['Brand System', 'InDesign', 'Photoshop'],
        year: '2023',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'ui-ux-design',
    number: '03',
    icon: '🎯',
    titleKey: 'uiux_title',
    subtitleKey: 'uiux_subtitle',
    descriptionKey: 'uiux_desc',
    fullDescriptionKey: 'uiux_full_desc',
    tools: ['Figma', 'Adobe XD', 'Framer', 'Maze', 'Protopie', 'FigJam'],
    categoryKey: 'cat_design',
    process: [
      { step: '01', titleKey: 'process_research', descKey: 'process_research_desc' },
      { step: '02', titleKey: 'process_wireframe', descKey: 'process_wireframe_desc' },
      { step: '03', titleKey: 'process_visual', descKey: 'process_visual_desc' },
      { step: '04', titleKey: 'process_prototype', descKey: 'process_prototype_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-ui-1',
        slug: 'mobile-app-design',
        titleKey: 'cs_mobile_design_title',
        categoryKey: 'cs_uiux_cat',
        image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80',
        excerptKey: 'cs_mobile_design_excerpt',
        tags: ['Figma', 'Protopie', 'Mobile'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-ui-2',
        slug: 'dashboard-redesign',
        titleKey: 'cs_dashboard_redesign_title',
        categoryKey: 'cs_uiux_cat',
        image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80',
        excerptKey: 'cs_dashboard_redesign_excerpt',
        tags: ['Figma', 'Design System', 'Usability'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-ui-3',
        slug: 'e-learning-platform',
        titleKey: 'cs_elearning_title',
        categoryKey: 'cs_uiux_cat',
        image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&q=80',
        excerptKey: 'cs_elearning_excerpt',
        tags: ['Figma', 'Adobe XD', 'Gamification'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
    ],
  },
  {
    slug: 'mobile-app',
    number: '04',
    icon: '📱',
    titleKey: 'mobile_title',
    subtitleKey: 'mobile_subtitle',
    descriptionKey: 'mobile_desc',
    fullDescriptionKey: 'mobile_full_desc',
    tools: ['React Native', 'Expo', 'Firebase', 'Swift', 'TypeScript', 'Redux'],
    categoryKey: 'cat_development',
    process: [
      { step: '01', titleKey: 'process_strategy', descKey: 'process_strategy_desc' },
      { step: '02', titleKey: 'process_design', descKey: 'process_design_desc' },
      { step: '03', titleKey: 'process_dev_mobile', descKey: 'process_dev_mobile_desc' },
      { step: '04', titleKey: 'process_launch_app', descKey: 'process_launch_app_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-mob-1',
        slug: 'fitness-tracker-app',
        titleKey: 'cs_fitness_title',
        categoryKey: 'cs_mobile_cat',
        image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        excerptKey: 'cs_fitness_excerpt',
        tags: ['React Native', 'Firebase', 'HealthKit'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-mob-2',
        slug: 'food-delivery-app',
        titleKey: 'cs_food_delivery_title',
        categoryKey: 'cs_mobile_cat',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80',
        excerptKey: 'cs_food_delivery_excerpt',
        tags: ['React Native', 'Stripe', 'Maps API'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-mob-3',
        slug: 'travel-planner-app',
        titleKey: 'cs_travel_title',
        categoryKey: 'cs_mobile_cat',
        image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80',
        excerptKey: 'cs_travel_excerpt',
        tags: ['Expo', 'TypeScript', 'OpenAI API'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
    ],
  },
  {
    slug: 'web-hosting',
    number: '05',
    icon: '☁️',
    titleKey: 'hosting_title',
    subtitleKey: 'hosting_subtitle',
    descriptionKey: 'hosting_desc',
    fullDescriptionKey: 'hosting_full_desc',
    tools: ['AWS', 'Vercel', 'Cloudflare', 'Docker', 'Nginx', 'GitHub Actions'],
    categoryKey: 'cat_infrastructure',
    process: [
      { step: '01', titleKey: 'process_assessment', descKey: 'process_assessment_desc' },
      { step: '02', titleKey: 'process_setup', descKey: 'process_setup_desc' },
      { step: '03', titleKey: 'process_migration', descKey: 'process_migration_desc' },
      { step: '04', titleKey: 'process_monitoring', descKey: 'process_monitoring_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-host-1',
        slug: 'ecommerce-infrastructure',
        titleKey: 'cs_ecommerce_infra_title',
        categoryKey: 'cs_hosting_cat',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80',
        excerptKey: 'cs_ecommerce_infra_excerpt',
        tags: ['AWS', 'Cloudflare', 'Docker'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-host-2',
        slug: 'multi-site-hosting',
        titleKey: 'cs_multisite_title',
        categoryKey: 'cs_hosting_cat',
        image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=80',
        excerptKey: 'cs_multisite_excerpt',
        tags: ['Nginx', 'Docker', 'GitHub Actions'],
        year: '2023',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'performance',
    number: '06',
    icon: '⚡',
    titleKey: 'performance_title',
    subtitleKey: 'performance_subtitle',
    descriptionKey: 'performance_desc',
    fullDescriptionKey: 'performance_full_desc',
    tools: ['Lighthouse', 'WebPageTest', 'Webpack', 'CDN', 'Chrome DevTools', 'GTmetrix'],
    categoryKey: 'cat_infrastructure',
    process: [
      { step: '01', titleKey: 'process_audit', descKey: 'process_audit_desc' },
      { step: '02', titleKey: 'process_diagnosis', descKey: 'process_diagnosis_desc' },
      { step: '03', titleKey: 'process_optimization', descKey: 'process_optimization_desc' },
      { step: '04', titleKey: 'process_verification', descKey: 'process_verification_desc' },
    ],
    caseStudies: [
      {
        id: 'cs-perf-1',
        slug: 'saas-speed-optimization',
        titleKey: 'cs_saas_speed_title',
        categoryKey: 'cs_performance_cat',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
        excerptKey: 'cs_saas_speed_excerpt',
        tags: ['Lighthouse', 'Webpack', 'CDN'],
        year: '2023',
        liveUrl: null,
      },
      {
        id: 'cs-perf-2',
        slug: 'ecommerce-speed-boost',
        titleKey: 'cs_ecommerce_speed_title',
        categoryKey: 'cs_performance_cat',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80',
        excerptKey: 'cs_ecommerce_speed_excerpt',
        tags: ['Core Web Vitals', 'Image CDN', 'Caching'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-perf-3',
        slug: 'news-portal-optimization',
        titleKey: 'cs_news_portal_title',
        categoryKey: 'cs_performance_cat',
        image: 'https://images.unsplash.com/photo-1504711434969-e33886168d9c?w=1200&q=80',
        excerptKey: 'cs_news_portal_excerpt',
        tags: ['GTmetrix', 'Cloudflare', 'Lazy Loading'],
        year: '2024',
        liveUrl: null,
      },
    ],
  },
]

export const getServiceBySlug = (slug) =>
  servicesData.find((s) => s.slug === slug) || null

export const serviceCategories = [
  ...new Set(servicesData.map((s) => s.categoryKey)),
]

export const serviceCategoryCounts = serviceCategories.map((cat) => ({
  nameKey: cat,
  count: servicesData.filter((s) => s.categoryKey === cat).length,
}))
