export const servicesData = [
  {
    slug: 'web-development',
    number: '01',
    icon: '🌐',
    title: 'Web Development',
    subtitle: 'Building the web, one pixel at a time',
    description:
      'From simple landing pages to complex web applications, we build fast, scalable and SEO-friendly websites tailored to your business needs. Our development process combines modern frameworks with battle-tested practices to deliver sites that perform.',
    fullDescription:
      'We specialize in building modern, high-performance web applications using cutting-edge technologies. Our team handles everything from initial architecture to deployment and optimization. Whether you need a marketing site, a complex SaaS dashboard, or an e-commerce platform, we deliver solutions that are fast, accessible, and built to scale.',
    tools: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL'],
    category: 'Development',
    process: [
      { step: '01', title: 'Discovery', desc: 'Understanding your business goals, target audience, and technical requirements.' },
      { step: '02', title: 'Architecture', desc: 'Planning the tech stack, database schema, and system architecture.' },
      { step: '03', title: 'Development', desc: 'Building with clean code, component-driven design, and continuous testing.' },
      { step: '04', title: 'Launch & Support', desc: 'Deployment, performance monitoring, and ongoing maintenance.' },
    ],
    caseStudies: [
      {
        id: 'cs-web-1',
        slug: 'e-commerce-platform',
        title: 'E-Commerce Platform',
        category: 'Web Development',
        image: 'https://images.unsplash.com/photo-1661956602116-aa6865609028?w=1200&q=80',
        excerpt: 'A fully custom e-commerce platform built with Next.js, featuring product filtering, cart management, and Stripe payments.',
        tags: ['Next.js', 'Stripe', 'Sanity CMS'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-web-2',
        slug: 'saas-dashboard',
        title: 'SaaS Dashboard',
        category: 'Web Development',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
        excerpt: 'A high-performance analytics dashboard with real-time data visualization and role-based access.',
        tags: ['Next.js', 'TypeScript', 'Recharts'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-web-3',
        slug: 'fintech-web-app',
        title: 'Fintech Web App',
        category: 'Web Development',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
        excerpt: 'A secure financial management platform with real-time transaction tracking and multi-currency support.',
        tags: ['React', 'Node.js', 'PostgreSQL'],
        year: '2024',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'graphics-design',
    number: '02',
    icon: '🎨',
    title: 'Graphics Design',
    subtitle: 'Visual storytelling that captivates',
    description:
      'We craft compelling visual identities — logos, brand guidelines, marketing materials and digital assets that make your brand stand out in a crowded market.',
    fullDescription:
      'Great design is more than aesthetics — it communicates your brand\'s values, builds trust, and drives action. We create everything from logo systems and brand guidelines to marketing collateral and social media assets. Every design is intentional, scalable, and crafted to leave a lasting impression.',
    tools: ['Illustrator', 'Photoshop', 'Canva', 'After Effects', 'InDesign', 'Figma'],
    category: 'Design',
    process: [
      { step: '01', title: 'Brief & Research', desc: 'Deep-diving into your brand, audience, and competitive landscape.' },
      { step: '02', title: 'Concepts', desc: 'Exploring multiple creative directions through mood boards and sketches.' },
      { step: '03', title: 'Refinement', desc: 'Iterating on the chosen direction until every detail is perfect.' },
      { step: '04', title: 'Delivery', desc: 'Handing off production-ready files in all formats with usage guidelines.' },
    ],
    caseStudies: [
      {
        id: 'cs-gfx-1',
        slug: 'branding-identity',
        title: 'Branding Identity',
        category: 'Branding',
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&q=80',
        excerpt: 'A complete brand identity system including logo, typography, color palette, and guidelines for a modern startup.',
        tags: ['Branding', 'Logo', 'Guidelines'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-gfx-2',
        slug: 'logo-design-collection',
        title: 'Logo Design Collection',
        category: 'Branding',
        image: 'https://images.unsplash.com/photo-1524532787116-e70228437bbe?w=1200&q=80',
        excerpt: 'A curated collection of logo marks crafted for businesses across various industries.',
        tags: ['Logo Design', 'Illustrator'],
        year: '2025',
        liveUrl: null,
      },
      {
        id: 'cs-gfx-3',
        slug: 'brand-identity-system',
        title: 'Brand Identity System',
        category: 'Branding',
        image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=1200&q=80',
        excerpt: 'Full brand identity system including visual language, marketing collateral, and digital assets.',
        tags: ['Brand System', 'InDesign', 'Photoshop'],
        year: '2023',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'ui-ux-design',
    number: '03',
    icon: '🎯',
    title: 'UI/UX Design',
    subtitle: 'Interfaces people love to use',
    description:
      'We design user interfaces that are beautiful, functional and conversion-focused. Every pixel is intentional, every interaction is smooth.',
    fullDescription:
      'User experience isn\'t just about pretty screens — it\'s about understanding behavior, reducing friction, and guiding users toward their goals. We combine research-driven insights with pixel-perfect design to create interfaces that feel effortless. From wireframes to high-fidelity prototypes, we design with empathy and precision.',
    tools: ['Figma', 'Adobe XD', 'Framer', 'Maze', 'Protopie', 'FigJam'],
    category: 'Design',
    process: [
      { step: '01', title: 'User Research', desc: 'Interviews, surveys, and competitor analysis to understand real user needs.' },
      { step: '02', title: 'Wireframing', desc: 'Low-fidelity wireframes to map out user flows and information architecture.' },
      { step: '03', title: 'Visual Design', desc: 'High-fidelity mockups with your brand\'s visual language and design system.' },
      { step: '04', title: 'Prototyping & Testing', desc: 'Interactive prototypes tested with real users for validation.' },
    ],
    caseStudies: [
      {
        id: 'cs-ui-1',
        slug: 'mobile-app-design',
        title: 'Mobile App Design',
        category: 'UI/UX',
        image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80',
        excerpt: 'End-to-end UI/UX design for a fitness tracking mobile app, from wireframes to high-fidelity prototypes.',
        tags: ['Figma', 'Protopie', 'Mobile'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-ui-2',
        slug: 'dashboard-redesign',
        title: 'SaaS Dashboard Redesign',
        category: 'UI/UX',
        image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80',
        excerpt: 'A complete redesign of a B2B analytics dashboard, reducing task completion time by 40%.',
        tags: ['Figma', 'Design System', 'Usability'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-ui-3',
        slug: 'e-learning-platform',
        title: 'E-Learning Platform',
        category: 'UI/UX',
        image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&q=80',
        excerpt: 'UI/UX design for an online learning platform with gamification elements and progress tracking.',
        tags: ['Figma', 'Adobe XD', 'Gamification'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
    ],
  },
  {
    slug: 'mobile-app',
    number: '04',
    icon: '📱',
    title: 'Mobile App Development',
    subtitle: 'Native experience, cross-platform power',
    description:
      'We build cross-platform mobile apps for iOS and Android using React Native — one codebase, native performance, seamless experience.',
    fullDescription:
      'Mobile is where your users are. We build high-quality cross-platform mobile applications that feel native on both iOS and Android. Using React Native and Expo, we deliver apps faster without sacrificing quality — with smooth animations, offline support, and push notifications built in.',
    tools: ['React Native', 'Expo', 'Firebase', 'Swift', 'TypeScript', 'Redux'],
    category: 'Development',
    process: [
      { step: '01', title: 'Strategy', desc: 'Defining core features, platform requirements, and go-to-market plan.' },
      { step: '02', title: 'Design', desc: 'Creating platform-aware designs following iOS and Android guidelines.' },
      { step: '03', title: 'Development', desc: 'Building with React Native, integrating APIs, and continuous testing.' },
      { step: '04', title: 'Launch', desc: 'App store submission, beta testing, and post-launch analytics setup.' },
    ],
    caseStudies: [
      {
        id: 'cs-mob-1',
        slug: 'fitness-tracker-app',
        title: 'Fitness Tracker App',
        category: 'Mobile App',
        image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        excerpt: 'A cross-platform fitness app with workout tracking, social features, and real-time health metrics.',
        tags: ['React Native', 'Firebase', 'HealthKit'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-mob-2',
        slug: 'food-delivery-app',
        title: 'Food Delivery App',
        category: 'Mobile App',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80',
        excerpt: 'A real-time food delivery app with GPS tracking, in-app payments, and restaurant management dashboard.',
        tags: ['React Native', 'Stripe', 'Maps API'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-mob-3',
        slug: 'travel-planner-app',
        title: 'Travel Planner App',
        category: 'Mobile App',
        image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80',
        excerpt: 'An AI-powered travel planning app with itinerary builder, offline maps, and budget tracking.',
        tags: ['Expo', 'TypeScript', 'OpenAI API'],
        year: '2023',
        liveUrl: 'https://example.com',
      },
    ],
  },
  {
    slug: 'web-hosting',
    number: '05',
    icon: '☁️',
    title: 'Web Hosting',
    subtitle: 'Reliable infrastructure, zero downtime',
    description:
      'We provide managed hosting solutions with daily backups, SSL certificates, CDN integration and 24/7 monitoring so you never go offline.',
    fullDescription:
      'Your website deserves infrastructure that never lets you down. We provide fully managed hosting with SSD storage, automatic daily backups, free SSL, global CDN integration, and 24/7 uptime monitoring. Whether you\'re running a small business site or a high-traffic platform, we keep you online and fast.',
    tools: ['AWS', 'Vercel', 'Cloudflare', 'Docker', 'Nginx', 'GitHub Actions'],
    category: 'Infrastructure',
    process: [
      { step: '01', title: 'Assessment', desc: 'Analyzing your traffic patterns, storage needs, and performance requirements.' },
      { step: '02', title: 'Setup', desc: 'Configuring servers, SSL, CDN, and automated backup systems.' },
      { step: '03', title: 'Migration', desc: 'Zero-downtime migration from your current host with full testing.' },
      { step: '04', title: 'Monitoring', desc: '24/7 uptime monitoring, auto-scaling, and proactive maintenance.' },
    ],
    caseStudies: [
      {
        id: 'cs-host-1',
        slug: 'ecommerce-infrastructure',
        title: 'E-Commerce Infrastructure',
        category: 'Hosting',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80',
        excerpt: 'Scalable hosting setup for a high-traffic e-commerce store handling 100K+ monthly visitors with zero downtime.',
        tags: ['AWS', 'Cloudflare', 'Docker'],
        year: '2024',
        liveUrl: null,
      },
      {
        id: 'cs-host-2',
        slug: 'multi-site-hosting',
        title: 'Multi-Site Hosting Setup',
        category: 'Hosting',
        image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=80',
        excerpt: 'Managed hosting for a network of 12 WordPress sites with shared resources and centralized monitoring.',
        tags: ['Nginx', 'Docker', 'GitHub Actions'],
        year: '2023',
        liveUrl: null,
      },
    ],
  },
  {
    slug: 'performance',
    number: '06',
    icon: '⚡',
    title: 'Performance Optimization',
    subtitle: 'Speed that converts',
    description:
      'We audit your site, fix bottlenecks and optimize every layer — images, code, server response — to achieve perfect Lighthouse scores.',
    fullDescription:
      'Every second of load time costs you conversions. We perform comprehensive speed audits, fix Core Web Vitals issues, optimize images and code bundles, implement CDN caching strategies, and fine-tune server configurations. The result: blazing-fast sites that rank higher and convert better.',
    tools: ['Lighthouse', 'WebPageTest', 'Webpack', 'CDN', 'Chrome DevTools', 'GTmetrix'],
    category: 'Infrastructure',
    process: [
      { step: '01', title: 'Audit', desc: 'Comprehensive performance audit with Lighthouse, WebPageTest, and real-user metrics.' },
      { step: '02', title: 'Diagnosis', desc: 'Identifying bottlenecks in code, images, fonts, server response, and third-party scripts.' },
      { step: '03', title: 'Optimization', desc: 'Implementing fixes — code splitting, image optimization, caching, lazy loading.' },
      { step: '04', title: 'Verification', desc: 'Re-testing, monitoring, and documenting improvements with before/after reports.' },
    ],
    caseStudies: [
      {
        id: 'cs-perf-1',
        slug: 'saas-speed-optimization',
        title: 'SaaS Dashboard Speed Boost',
        category: 'Performance',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
        excerpt: 'Reduced dashboard load time from 6.2s to 1.1s through code splitting, lazy loading, and server optimization.',
        tags: ['Lighthouse', 'Webpack', 'CDN'],
        year: '2023',
        liveUrl: null,
      },
      {
        id: 'cs-perf-2',
        slug: 'ecommerce-speed-boost',
        title: 'E-Commerce Speed Boost',
        category: 'Performance',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80',
        excerpt: 'Achieved 98+ Lighthouse score for an e-commerce site, improving conversion rate by 23%.',
        tags: ['Core Web Vitals', 'Image CDN', 'Caching'],
        year: '2024',
        liveUrl: 'https://example.com',
      },
      {
        id: 'cs-perf-3',
        slug: 'news-portal-optimization',
        title: 'News Portal Optimization',
        category: 'Performance',
        image: 'https://images.unsplash.com/photo-1504711434969-e33886168d9c?w=1200&q=80',
        excerpt: 'Optimized a high-traffic news portal serving 500K+ page views/month with aggressive caching and lazy loading.',
        tags: ['GTmetrix', 'Cloudflare', 'Lazy Loading'],
        year: '2024',
        liveUrl: null,
      },
    ],
  },
]

// Helpers
export const getServiceBySlug = (slug) =>
  servicesData.find((s) => s.slug === slug) || null

export const serviceCategories = [
  ...new Set(servicesData.map((s) => s.category)),
]

export const serviceCategoryCounts = serviceCategories.map((cat) => ({
  name: cat,
  count: servicesData.filter((s) => s.category === cat).length,
}))